---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Scan for secrets

on:
  push:
    branches:
      - "**"

jobs:
  scan-for-secrets:
    name: Scan for secrets
    uses: wetransform/gha-workflows/.github/workflows/scan-for-secrets.yml@2740e518e1d9ea2e965a901281e051ea26e3512c # v4.1.0
    %{~ if owner == "wetransform" ~}
    secrets: inherit
    %{~ else ~}
    secrets:
      SLACK_EXPOSED_SECRETS_WEBHOOK: $${{ secrets.SLACK_EXPOSED_SECRETS_WEBHOOK }}
    %{~ endif ~}
